### ISSUE TITLE
Twitter Trends 

### ISSUE THREAD

**Issue by bdr0id** [l00pinfinity/api.birdapp#1]
* When a tweet is posted, track how many hashtags were used, as well as the number of times they were used, in the database.
* The trending hashtags can be sorted in descending order by their usage count by using Spring Boot's scheduling capabilities.

**Comment by StanleyMasinde** [comment]
This sounds interesting. I can't wait to see your implementation.

**Comment by bdr0id** [comment]
@StanleyMasinde I think this will work for now 💯

**Comment by StanleyMasinde** [comment]
Looks good
